import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
import { clientsClaim } from 'workbox-core';

// Force new service worker to activate immediately
self.skipWaiting();
clientsClaim();

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// Clean up old precaches from previous builds
cleanupOutdatedCaches();

// Listen for messages from client (e.g. Socket.IO bridge)
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SHOW_NOTIFICATION') {
    const { title, body, icon, badge, tag, data } = event.data.payload;

    // Show OS system notification
    event.waitUntil(
      self.registration.showNotification(title, {
        body,
        icon,
        badge,
        tag,
        data,
        vibrate: [100, 50, 100],
        data: data // Pass custom data like redirection link
      })
    );
  }
});

// Handle user clicking the OS notification
self.addEventListener('notificationclick', (event) => {
  event.notification.close(); // Close the notification banner

  const relativeLink = event.notification.data?.link || '/dashboard/notifications';
  const urlToOpen = new URL(relativeLink, self.location.origin).href;

  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windowClients) => {
      // Try to find an existing open tab/window and focus it
      for (let i = 0; i < windowClients.length; i++) {
        const client = windowClients[i];
        if ('focus' in client) {
          // Send navigation message or try to navigate client directly if possible
          // For simplicity, if we are already on that domain, navigate and focus
          client.navigate(urlToOpen);
          return client.focus();
        }
      }
      
      // If no active window exists, open a new one
      if (self.clients.openWindow) {
        return self.clients.openWindow(urlToOpen);
      }
    })
  );
});
